### ISSUE TITLE
Unable to Connect to Phone with rsa-sha2-256 key

### ISSUE THREAD

**Issue by brettrbarker** [brettrbarker/avaya-1100-pdt-tool#9]
```
Exception (client): Invalid key (class: RSAKey, data type: rsa-sha2-256
Traceback (most recent call last):
  File "/home/brett.barker/.local/lib/python3.6/site-packages/paramiko/transport.py", line 2129, in run
    self.kex_engine.parse_next(ptype, m)
  File "/home/brett.barker/.local/lib/python3.6/site-packages/paramiko/kex_group1.py", line 75, in parse_next
    return self._parse_kexdh_reply(m)
  File "/home/brett.barker/.local/lib/python3.6/site-packages/paramiko/kex_group1.py", line 120, in _parse_kexdh_reply
    self.transport._verify_key(host_key, sig)
  File "/home/brett.barker/.local/lib/python3.6/site-packages/paramiko/transport.py", line 1937, in _verify_key
    key = self._key_info[self.host_key_type](Message(host_key))
  File "/home/brett.barker/.local/lib/python3.6/site-packages/paramiko/rsakey.py", line 76, in __init__
    cert_type="ssh-rsa-cert-v01@openssh.com",
  File "/home/brett.barker/.local/lib/python3.6/site-packages/paramiko/pkey.py", line 622, in _check_type_and_load_cert
    raise SSHException(err.format(self.__class__.__name__, type_))
paramiko.ssh_exception.SSHException: Invalid key (class: RSAKey, data type: rsa-sha2-256

```

**Comment by brettrbarker** [comment]
Possible workaround to look at with older paramiko version.
https://stackoverflow.com/questions/70604571/paramiko-2-9-is-failing-with-invalid-key-class-rsakey-data-type-rsa-sha2-25

**Comment by brettrbarker** [comment]
Have not been able to reproduce on a test phone with same 04.04.42 firmware and same security policy file.

**Comment by brettrbarker** [comment]
Confirmed that older version (Paramiko 2.4.2) does not experience this issue. And once the new version has a known host key (via old, working version), it continues to work too unless the host key changes or gets removed.

**Comment by brettrbarker** [comment]
Version 1.6 removed known_phones (known hosts) requirement. The only workaround for this issue is to use an older paramiko version.
